kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "helloworld-build"
spec:
  runPolicy: "Serial"
  source:
    type: "Binary"
    binary:
      asFile: "helloworld.jar"
  strategy:
    type: "Docker"
    dockerStrategy:
      dockerfilePath: Dockerfile
      env:
        - name: "BUILD_LOGLEVEL"
          value: "5"