kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "helloworld-build"
spec:
  runPolicy: "Serial"
  source:
    type: "Binary"
  strategy:
    type: "Docker"
    dockerStrategy:
      dockerfilePath: Dockerfile
      env:
        - name: "BUILD_LOGLEVEL"
          value: "5"
  output:
    to:
      kind: "ImageStreamTag"
      name: "helloworld:v1"

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: helloworld-is
  labels:
    app: helloworld-app